version: "3.9"  # optional since v1.27.0
services:
  backend:
    build: ./back
    ports:
      - "3001:3000"
    depends_on:
      - database
    networks:
      - backend
  database:
    image: postgres
    expose:
      - "5432"
    volumes:
      - db-data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: password
  frontend:
    build: ./front
    ports:
      - "3000:3000"
    networks:
      - backend
volumes:
  db-data:
networks:
  backend:
